# Generated by Django 3.0.3 on 2020-02-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelProfile',
            new_name='Profile',
        ),
    ]
